### ISSUE TITLE
路线规划有吗

### ISSUE THREAD

**Issue by jsshizhan** [huiyan-fe/react-bmap#1]
根据起点终点规划驾车路线

**Comment by hinikai** [comment]
感谢反馈、目前还没有、后续会加上的~

**Comment by jsshizhan** [comment]
这个很简单啊，你们是不是打算弃坑了啊

**Comment by hinikai** [comment]
https://github.com/huiyan-fe/react-bmap/blob/master/docs/examples/components/driving-route.js
可参考这个示例、加了个驾车路径规划.

**Comment by jsshizhan** [comment]
我自己写啦 不过还是谢谢
