### ISSUE TITLE
new BMap报错

### ISSUE THREAD

**Issue by wangxinyu666666** [huiyan-fe/react-bmap#108]
这是在umi中引入百度地图api
![image](https://user-images.githubusercontent.com/26834996/119497283-f8b09c00-bd96-11eb-8a5f-0b697e47a8ec.png)
在tsx文件里使用new BMap报错
![image](https://user-images.githubusercontent.com/26834996/119497326-06662180-bd97-11eb-9d09-b07704c9ac74.png)
![image](https://user-images.githubusercontent.com/26834996/119497357-0cf49900-bd97-11eb-821e-2a7dbdc8f517.png)

**Comment by Junior2Ran** [comment]
npm install @types/bmap

**Comment by xwg2015** [comment]
> npm install @types/bmap

404 Not Found - GET https://registry.npmjs.com/@types%2fbmap - Not found
