### ISSUE TITLE
该库是否不支持点聚合？

### ISSUE THREAD

**Issue by CynthiaNC** [huiyan-fe/react-bmap#11]
[点聚合](http://developer.baidu.com/map/jsdemo.htm#c1_4) 的操作支持吗?

**Comment by fachilles** [comment]
这功能属于应用级开发

**Comment by zmofei** [comment]
可以参考 @fachilles 的意见，或者使用我们网格/蜂窝图，这两种绘制自动会根据地图的即便进行聚合之后再计算热力。
