### ISSUE TITLE
控件的 anchor属性如何设置才能生效？

### ISSUE THREAD

**Issue by fachilles** [huiyan-fe/react-bmap#13]
以NavigationControl控件为例：

<NavigationControl /> 如果要将其放在右下角，应该怎样设置才是正确的？
以下都不成功：

1:<NavigationControl anchor="BMAP_ANCHOR_BOTTOM_RIGHT" />
2:<NavigationControl anchor={"BMAP_ANCHOR_BOTTOM_RIGHT"} />

**Comment by fachilles** [comment]
还是使用CSS控制吧...

**Comment by Evanxuke** [comment]
遇到了同样的问题，百度应该有自己的类型定义

**Comment by Evanxuke** [comment]
所以 我就尝试性的 给了一个int类型的1 结果 移动到右上角去了 你可以去试试
