### ISSUE TITLE
请问如何捕捉 地图上的点击事件?

### ISSUE THREAD

**Issue by charrsId** [huiyan-fe/react-bmap#14]
让点击之后返可以回点击的位置信息，包括经纬度和中文地址？
万分感谢

**Comment by jonahfang** [comment]
为何关闭此问题，解决了吗？

**Comment by Dawson-Jiang** [comment]
我是这样写的，生效： 
ref={(a: any) => {
                if (a && a.map && !this.state.hasAddMapListener) {
                  a.map.addEventListener("click", this.mapClick)
                  this.setState({ hasAddMapListener: true })
                }
              }}>
