### ISSUE TITLE
NavigationControl NavigationControlType怎么设置

### ISSUE THREAD

**Issue by yishangtanhuan** [huiyan-fe/react-bmap#16]
<Map center={{
                    lng: 105.403119,
                    lat: 38.028658
                }}
                zoom='5' 
                mapStyle={simpleMapStyle}>
            <NavigationControl />
            <MapTypeControl />
            <ScaleControl />
            <OverviewMapControl />
        </Map>

代码中的控件类型怎么设置，比如NavigationControlType=BMAP_NAVIGATION_CONTROL_PAN，在react中怎么写呢

**Comment by Junior2Ran** [comment]
https://github.com/huiyan-fe/react-bmap/blob/master/docs/examples/components/control.js
react-bmap封装了几个常用控件，在`NavigationControl`控件中要设置其`type`属性可以直接传递参数，如下：
`<NavigationControl type={BMAP_NAVIGATION_CONTROL_ZOOM}/> `
