### ISSUE TITLE
请问组件能实现点聚合的功能吗？如果能，怎么实现

### ISSUE THREAD

**Issue by wangmhaha** [huiyan-fe/react-bmap#18]
因为项目需求，将会加载很多的点在地图上，怎么能实现点聚合的功能呢

**Comment by Junior2Ran** [comment]
[百度地图开放平台点聚合的开源库](http://api.map.baidu.com/library/MarkerClusterer/1.2/docs/help.html)
[MapV](https://mapv.baidu.com/)也可以实现
