### ISSUE TITLE
Uncaught ReferenceError: BMap is not defined

### ISSUE THREAD

**Issue by tommywu23** [huiyan-fe/react-bmap#20]
index.html
```
  <script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=eBGR7XzaPhB5UbYARl3E7ksdkMdgrCw7"></script>
```

package.json
```
  "dependencies": {
    "react-bmap": "^1.0.55",
```

React Components

```
import { Map } from 'react-bmap'

...
<Map center={{lng: 116.402544, lat: 39.928216}} zoom="12" />
```

runtime error:
Uncaught ReferenceError: BMap is not defined

**Comment by hinikai** [comment]
现在需要在页面中先引入jsapi的脚本，如
<script type="text/javascript" src="//api.map.baidu.com/api?v=2.0&ak=1XjLLEhZhQNUzd93EjU5nOGQ"></script>
还未做异步加载地图jsapi处理

**Comment by dingcaiying** [comment]
@huangxiaohao 在html里加就行了：
<script type="text/javascript" src="https://api.map.baidu.com/api?v=2.0&ak={appkey}"></script>
<script type="text/javascript">
    window.BMap = BMap;
</script>
<div id="app"></div>
...
