### ISSUE TITLE
CustomOverlay Markers 的事件在微信上没反应

### ISSUE THREAD

**Issue by chaileicsu** [huiyan-fe/react-bmap#22]
按照说明文档，在自定义覆盖物上增加了click事件，在chrom，fixfox等浏览器上都正常，但在微信开发工具及微信上，都没反应，查看div的eventListener 也显示有click；
代码如下
infoWindow = (<Marker id='showMarker'
          position={{lng: this.state.selectedLng, lat: this.state.selectedLat}} 
          offset={{width:-75, height:-60}} 
          events={{
                    click:(e) => {console.log('xxxxxxxxxx');}
                }}
          >
                <div onClick={function(){alert(1)}}
                style={{width: '150px', height: '40px', lineHeight: '40px',color:'#4c4c4c', background: '#fff', textAlign: 'center'}}>
                {orgInfo.organizationAbbreviation}
                </div>
          </Marker>);

请问有朋友遇到过吗；

**Comment by Junior2Ran** [comment]
question out of date, closed.
