### ISSUE TITLE
地图背景没出来

### ISSUE THREAD

**Issue by dmpx** [huiyan-fe/react-bmap#23]
html 中引入     <script type="text/javascript" src="http://api.map.baidu.com/api?v=3.0&ak=IyGVKYvZPosRG9BI1xwEonR80VVCwq"></script>

`export default class BaiduMap extends Component {
  render() {
    return (
      <Map center={{lng: 116.375523, lat: 39.918255}} zoom='15'>
        <Marker position={{lng: 116.375523, lat: 39.918255}} />
        <NavigationControl />
        <InfoWindow position={{lng: 116.375523, lat: 39.918255}} title='标题' text='内容' />
      </Map>
    )
  }
}`

[图片](http://x.redbon.com.cn/uploads/map.png)

**Comment by Junior2Ran** [comment]
打开`console`看看报什么错了吗？
