### ISSUE TITLE
MapvLayer上画的LineString，click事件有问题

### ISSUE THREAD

**Issue by chy1112** [huiyan-fe/react-bmap#24]
1.我在地图上画了很多线。类似于一个城市的所有公交路线，然后methods中配置了click属性，click对应的函数中只有一句consloe.log。结果是在距离线比较远的地方点击，在控制台输出线的坐标而不是null，当然有些地方还是会输出null。（chrome 浏览器）

2.在microsoft edge中点击线条，会报错Object doesn't support property or method 'isPointInStroke'

**Comment by Junior2Ran** [comment]
首先建议您使用chrome浏览器，其他浏览器不知道会产生什么奇怪的兼容问题
其次顾名思义，isPointInStroke是依赖库mapv的方法，作用是判断点击事件发生的点有没有在画的线上，可能这个方法有一些问题，可以进一步看一下
