### ISSUE TITLE
<DrivingRoute/>组件调用报错

### ISSUE THREAD

**Issue by purpletastes** [huiyan-fe/react-bmap#26]
我的调用方式： <DrivingRoute  start='大竹林' end='重庆北站'/>

BMAP_DRIVING_POLICY_LEAST_TIME 这个参数未定义，应该怎么传参或者调用？

**Comment by Junior2Ran** [comment]
https://github.com/huiyan-fe/react-bmap/blob/master/docs/examples/components/driving-route.js
参考上述示例来调用。start和end参数可以为BMap.Point或者城市名。

BMAP_DRIVING_POLICY_LEAST_TIME 这个参数是表示驾车方案的策略配置为最少时间策略。
