### ISSUE TITLE
组件是否支持CSS-Modules

### ISSUE THREAD

**Issue by carryonZhang** [huiyan-fe/react-bmap#3]
想在Map上中使用CSS-Modules的方式写样式：
import style from './style.css'
class Location extends Component {
  render() {
    return 
    \<Map style={style.location} center={{lng: 105.403119, lat: 38.028658}} zoom='5'>
\</Map>
  }
}
export default Location
但是到了页面上发现样式没进来

**Comment by hinikai** [comment]
这是你们项目中的代码吧？webpack可以使用css-loader来在js中加载样式，现在我们还没有用到样式所以没配置

**Comment by carryonZhang** [comment]
犯了个低级错误，应该写成className={style.location}
