### ISSUE TITLE
安装上后报错提示没有mapv maptalks 把这些都安装了还是报错

### ISSUE THREAD

**Issue by Jarryxin** [huiyan-fe/react-bmap#33]
mapv.js?2ba4:220 Uncaught TypeError: Super expression must either be null or a function, not undefined

**Comment by kewanglantian** [comment]
同问

**Comment by Lpbzzz** [comment]
求解，现在解决了吗

**Comment by GlimmerYXY** [comment]
急！

**Comment by Lpbzzz** [comment]
安装 maptalks@0.39.8，具体原因见maptalks的ISSUES

**Comment by Lpbzzz** [comment]
@unclepis 直接安的0.40.2吗?

**Comment by unclepis** [comment]
@Lpbzzz  嗯嗯，直接安装的就是上面的版本，写了个demo也没报啥错

**Comment by Jarryxin** [comment]
我没有用这个了 ，直接在首页引入百度地图 js,然后 在页面组件挂载后的生命周期对相应的dom加载百度地图，就可以了 。

**Comment by Junior2Ran** [comment]
#38 
报错没有安装maptalks已更新，及时更新react-bmap即可
