### ISSUE TITLE
infoWindow的content不能支持react组件么？只能纯文本？

### ISSUE THREAD

**Issue by unclepis** [huiyan-fe/react-bmap#35]
![image](https://user-images.githubusercontent.com/22478908/41081398-4678d302-6a5d-11e8-9989-f2a09f047471.png)
如图，给infoWindow的内容传入一个react组件，弹出Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'. 应该是不支持reactNode类型

**Comment by lf7817** [comment]
```js
var opts = {};
this.infoWindow = new BMap.InfoWindow(this.props.text, this.getOptions(this.options));  // 创建信息窗口对象 
this.bindEvent(this.infoWindow, this.events);
```
源码中没有处理text，只能是html元素，只能修改源码， 用ReactDom.render处理下。
我直接拷贝了源码，自己封装个infobox组件，内容随便写

**Comment by Dongsw08** [comment]
可以直接把content用ReactDOMServer.renderToStaticMarkup转化一下再传进去
