### ISSUE TITLE
Module not found: Can't resolve 'maptalks'

### ISSUE THREAD

**Issue by nvsky** [huiyan-fe/react-bmap#38]
![image](https://user-images.githubusercontent.com/8436965/41587035-cfad13ea-73e0-11e8-8a17-ef20770156b2.png)
![image](https://user-images.githubusercontent.com/8436965/41587274-65351354-73e1-11e8-8377-6be89d0a9c5a.png)

**Comment by hinikai** [comment]
可以先安装个这个maptalks，后续要把mapv图层单独抽离出来

**Comment by Junior2Ran** [comment]
@nvsky 该问题是由于mapv版本升级导致的，现已通过固定依赖mapv版本解决。
更新react-bmap即可
