### ISSUE TITLE
地图mapStyle问题

### ISSUE THREAD

**Issue by Lpbzzz** [huiyan-fe/react-bmap#47]
现在有一个需求是修改地图的mapStyle：
![image](https://user-images.githubusercontent.com/28721487/45282605-f8501400-b50d-11e8-8ea4-bfd2ffb05289.png)
下拉框修改地图样式，但却没生效，不知为何，还望解答。谢谢

**Comment by Junior2Ran** [comment]
可以，写个changeMapStyle方法

    changeMapStyle(style) {
        this.setState({
            style: style
        });
        this.props.map.setMapStyle({style: style});
    }

**Comment by Lpbzzz** [comment]
不好意思。。setMapStyle 这是个react-bmap里的API吗？this.props.map指的是
![_20181220115926](https://user-images.githubusercontent.com/28721487/50263007-bf013b80-044e-11e9-93da-4b7ebcca1276.png)这个吗？

**Comment by Junior2Ran** [comment]
1.`setMapStyle`是百度地图原生的[jsapi](http://lbsyun.baidu.com/cms/jsapi/reference/jsapi_reference.html#a0b0)，所以要获取到原生js的map实例化对象。react-bmap也将这个map对象放到了每个子组件的props里

    return React.Children.map(children, child => {
        if (!child) {
            return;
        }
        if (typeof child.type === 'string') {
            return child;
        } else {
            return React.cloneElement(child, {
                map: this.map
            });
        }
    })

2.是的
