### ISSUE TITLE
Mac 下切换地图显示类型,在render的时候没有反应. Windows 是正常的

### ISSUE THREAD

**Issue by dongjian** [huiyan-fe/react-bmap#48]
源码如下

export const BaiduMapView = withScriptjsBaidu({
    key: '',
    render: (B: any, props: BaiduMapViewProps) =>
        <B.Map
            center={props.curPostion}
            zoom={16}
            style={{ height: '100%' }}
            enableScrollWheelZoom={true}
        >
            {props.path.map((v, i) => {
                return <B.Polyline
                    key={i}
                    strokeColor='red'
                    path={v}
                />
            })}

            <B.Marker position={props.curPostion}>
                {props.curPostion.lat == 0 && props.curPostion.lng == 0 ? null : <Car rotation={props.curPostion.roation} />}
            </B.Marker>
            <B.MapTypeControl />
        </B.Map>
})

**Comment by Junior2Ran** [comment]
抱歉看不清源码，也没有看到切换地图类型的代码。
您在书写`markdown`的时候可以使用```符号把您的代码包裹起来，以提高可读性
