### ISSUE TITLE
Marker图标icon不识别

### ISSUE THREAD

**Issue by carryonZhang** [huiyan-fe/react-bmap#5]
按照文档想设置一个蓝色带数字的Marker，但是在项目里不识别
<img width="668" alt="2017-08-25 11 19 43" src="https://user-images.githubusercontent.com/20091023/29698342-5d5e9834-8987-11e7-8e84-d1457a067e8c.png">
<img width="405" alt="2017-08-25 11 20 53" src="https://user-images.githubusercontent.com/20091023/29698363-80e49cf4-8987-11e7-9a0f-92ceb7971f96.png">

**Comment by hinikai** [comment]
现在蓝色带数字的还没有，只有red1，red2，后续我会也加上个蓝色的

**Comment by carryonZhang** [comment]
我这个伸手党在这先谢谢你啦。
