### ISSUE TITLE
地图Maker->自定义覆盖物的transition问题

### ISSUE THREAD

**Issue by Lpbzzz** [huiyan-fe/react-bmap#50]
```
<Marker
            position={{lng: 116.402544, lat: 39.929543}}
            offset={new BMap.Size(10, -150)}>
<div style里写transition>

</div>
</Marker>
```
这个transition，在div改变样式的时候不能正确生效。不知何解，还望解答

**Comment by Junior2Ran** [comment]
是的，你可以观察[`Marker.js`](https://github.com/huiyan-fe/react-bmap/blob/master/src/components/marker.js)组件的生命周期变化，在执行`destroy()`的时候，之前的`marker`会被移除。

**Comment by Lpbzzz** [comment]
@Junior2Ran 明白了。手动写了个渐变。多谢解答。
