### ISSUE TITLE
NavigationControl组件显示异常

### ISSUE THREAD

**Issue by li-changyu** [huiyan-fe/react-bmap#52]
![image](https://user-images.githubusercontent.com/27916327/50087635-aec54280-023b-11e9-8e39-6c0fd408ef73.png)
在type为BMAP_NAVIGATION_CONTROL_LARGE和BMAP_NAVIGATION_CONTROL_SMALL时会出现如图上的显示异常

**Comment by Junior2Ran** [comment]
本地无法复现，能否提供可复现的预览链接？
