### ISSUE TITLE
Road覆盖物，在用鼠标拖动地图之后重影

### ISSUE THREAD

**Issue by TornParadise** [huiyan-fe/react-bmap#53]
![1545104429 1](https://user-images.githubusercontent.com/33707375/50131008-2edebd00-02bb-11e9-82e6-8289bf2e3078.jpg)

chrome版本 71.0.3578.98（正式版本） （64 位）

**Comment by Junior2Ran** [comment]
本地无法复现，能否提供可复现的预览链接？
