### ISSUE TITLE
百度地图3.0版本

### ISSUE THREAD

**Issue by liujinxiao** [huiyan-fe/react-bmap#54]
请问现在支持百度地图3.0版吗？

**Comment by Junior2Ran** [comment]
react-bmap只是对于BMap一个react的封装，首先您需要在页面头部引入jsapi
`<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=您的密钥"></script>`
如果您想要使用3.0版本的百度地图，在引入脚本时，将`v=2.0`修改为`v=3.0`，引入3.0版本的jsapi即可
