### ISSUE TITLE
您好！小弟写的地图很卡顿，希望您分析一下，求解答。

### ISSUE THREAD

**Issue by TornParadise** [huiyan-fe/react-bmap#55]
1.首先贴图
![default](https://user-images.githubusercontent.com/33707375/50511495-d84a5d80-0ac8-11e9-84bd-d0b7e385f9a4.png)
2.这个项目，不进入地图的路由（开发模式下）内存占用200MB左右，稳定。
3. 地图的基本业务逻辑：
    （1）200条左右的线+300个左右的Marker。
    （2）socket不停地更新这300个点的属性。
    （3）socket大概每次推送10个点，每10秒大概一波推送（3-5个）。
求您分析、解答一下：为什么很短的时间之内内存占用就会超级大，地图操作非常卡顿？
如果您有兴趣进一步了解一下`事故现场`，请联系lpb_name@163.com。
十分感谢您。

**Comment by Junior2Ran** [comment]
如果您是使用的原生Marker和Line来绘制的点与线，那么实际上您操作的是dom，不停的操作500个左右的dom本身就很影响性能。

建议您在大数据量的前提下，不要直接操作dom，可以使用canvas来绘制线和点，我们团队也有基于canvas的解决方案[mapV](https://mapv.baidu.com/)，根据您的描述应该会满足需求。

具体的可以看下mapV的[github](https://github.com/huiyan-fe/mapv)。
