### ISSUE TITLE
您好~百度地图官方似乎在地图中把公园的位置用花来显示了，如何能禁用掉呢？

### ISSUE THREAD

**Issue by Lpbzzz** [huiyan-fe/react-bmap#58]
![flower](https://user-images.githubusercontent.com/28721487/54808662-dc4add80-4cbb-11e9-8c25-d97459938659.png)

**Comment by Junior2Ran** [comment]
这是主站地图的默认底图，最近春天有赏樱花活动，所以有这么多🌸
单独禁用🌸没有办法，可以等这个活动结束，或者是更换一个稳定的个性化底图
