### ISSUE TITLE
当标记点非常多，地图及相关组件渲染非常慢

### ISSUE THREAD

**Issue by ahua52** [huiyan-fe/react-bmap#59]
使用场景介绍
我在地图上渲染Marker 数据量很多 有一两千左右。渲染的较慢
我的右键Marker 显示当前的infoWindow  显示的非常慢。
可否优化下 感谢！

**Comment by Junior2Ran** [comment]
如果您使用的是`<Marker/>`或者是`<MarkerList/>`组件，他们点的绘制是通过原生dom来实现的，新增一两千个dom结点确实对性能有影响。

建议在大数据量的情况下，不要直接操作dom，可以使用canvas来绘制点，我们团队也有基于canvas的解决方案[mapV](https://mapv.baidu.com/)，在`react-bmap`中可以直接使用`<MapvLayer/>`组件

至于mapV如何使用，可以查看[github](https://github.com/huiyan-fe/mapv)。
