### ISSUE TITLE
请问添加热力图的话该怎么操作

### ISSUE THREAD

**Issue by jjwong1991** [huiyan-fe/react-bmap#6]
http://developer.baidu.com/map/jsdemo.htm#c1_15
像这个Demo里面的
`heatmapOverlay = new BMapLib.HeatmapOverlay({"radius":20});`
`map.addOverlay(heatmapOverlay);`
`heatmapOverlay.setDataSet({data:points,max:100});`
如何把heatmapOverlay附加到Map上呢

**Comment by hinikai** [comment]
可以使用参考使用<MapvLayer />，把draw改成heatmap
https://github.com/huiyan-fe/react-bmap/blob/master/docs/examples/components/mapv-layer.js

**Comment by jjwong1991** [comment]
感谢，可以呈现热力图了，之前不知道还有Mapv这等神器
