### ISSUE TITLE
BMp undefined

### ISSUE THREAD

**Issue by mpw0311** [huiyan-fe/react-bmap#60]
new BMap 的时候BMap 的值是undefined，需要等一会儿才能有值，异步加载的问题么？如何解决

**Comment by Junior2Ran** [comment]
现在还未做异步加载地图jsapi处理，需要同步处理，先在页面中先[引入地图的jsapi的脚本](https://github.com/huiyan-fe/react-bmap/blob/master/README.md#%E5%AE%89%E8%A3%85%E4%BD%BF%E7%94%A8)

**Comment by Junior2Ran** [comment]
#20 #21 #39

**Comment by mpw0311** [comment]
好的，个人感觉您的项目非常不错，希望您能尽快实现异步加载
