### ISSUE TITLE
初始化地图位置不正确

### ISSUE THREAD

**Issue by Hwh520zyn** [huiyan-fe/react-bmap#61]
1. ![image](https://user-images.githubusercontent.com/35677000/57668658-94509300-763a-11e9-8683-b29cc76d8232.png)

2. 
![image](https://user-images.githubusercontent.com/35677000/57668677-a6cacc80-763a-11e9-899a-035beef37869.png)
初始化地图的时候，显示的是图1，但其实位置应该是图2，拖动地图的话，才会回到图2，以下是代码：

this.state={
         posi :{
                lng:  120.219375, 
                lat: 30.259245
          }
}

<Map ref={ref => this.map = ref.map}  center={this.state.posi}   zoom="13" >
          <Marker position={{lng: 120.219375, lat: 30.259245}} offset={new 
             global.BMap.Size(-15, -40)} >
                  <img src={require('../../../assets/img/shop/active_marker.png')} 
                          onClick={function(e){
                               console.log(e.currentTarget)
                          }
                   } 
                   className={styleCss.icon}alt=""/>
           </Marker>
 </Map>

**Comment by Junior2Ran** [comment]
state有变化吗，来个可访问链接看看
