### ISSUE TITLE
自定义动态生成infowindow的内容，如何给内容里的按钮添加点击事件

### ISSUE THREAD

**Issue by ahua52** [huiyan-fe/react-bmap#65]
场景是这样的：我有很多maker,  点击maker弹出对应的infowindow,  infowindow里显示自定义的内容。其中有个按钮  我想点击它触发一个事件。请问该怎么做？
十分感谢

**Comment by Junior2Ran** [comment]
不太明白您的意思，`<button onClick={()=>{console.log('click')}}/>`不就可以了吗

**Comment by ahua52** [comment]
不行的  infowindow里的内容是html拼接上去的  传到infowindow 是个dom字符串形式传给text参数 而且text 只能接受字符串形式的

**Comment by Junior2Ran** [comment]
同#71，已在#72 修复，更新到最新版本使用
