### ISSUE TITLE
点击Marker弹出InfoWindow的问题

### ISSUE THREAD

**Issue by carryonZhang** [huiyan-fe/react-bmap#7]
我想实现点击路径上的一个Marker，弹出一个InfoWindow，按照百度的api的写法，会报错。
![image](https://user-images.githubusercontent.com/20091023/29737818-bc01f5c8-8a47-11e7-9c4c-4b31cf582620.png)
![image](https://user-images.githubusercontent.com/20091023/29737830-034fde4a-8a48-11e7-89e5-97a0d44b1122.png)
是要按照你的插件的api来弹出InfoWindow吗？按照你的方式来写，该怎么写啊？

**Comment by hinikai** [comment]
可以在click的时候在Map下加一个<IndoWindow >的组件

**Comment by carryonZhang** [comment]
你好，我现在使用组件内的state的方式控制InfoWindow的显示与隐藏，但是发现state可以显示InfoWindow：
![image](https://user-images.githubusercontent.com/20091023/29740068-b06a5e9c-8a80-11e7-81f5-909f0e67c7d2.png)
但是再次点击Marker，InfoWindow隐藏了一下又出现了，
![image](https://user-images.githubusercontent.com/20091023/29740078-e6a0c866-8a80-11e7-832d-8284ac8cff47.png)
而且我看文档上Marker上面没有关闭InfoWindow的方法，怎么办？

**Comment by hinikai** [comment]
感谢您的反馈、刚发现有个bug，在componentWillUnmount时候没关闭infowindow，刚发布了个新版本，您试试

**Comment by mamiefeng** [comment]
> 你好，我现在使用组件内的state的方式控制InfoWindow的显示与隐藏，但是发现state可以显示InfoWindow：
> ![image](https://user-images.githubusercontent.com/20091023/29740068-b06a5e9c-8a80-11e7-81f5-909f0e67c7d2.png)
> 但是再次点击Marker，InfoWindow隐藏了一下又出现了，
> ![image](https://user-images.githubusercontent.com/20091023/29740078-e6a0c866-8a80-11e7-832d-8284ac8cff47.png)
> 可以看到visible的值已经变成false了，但是InfoWindow没关闭。
> 而且我看文档上Marker上面没有关闭InfoWindow的方法，
您好这个  使用组件内的state的方式控制InfoWindow的显示与隐藏，但是发现state可以显示是怎么做的
