### ISSUE TITLE
请问Marker是否支持图片资源的icon??

### ISSUE THREAD

**Issue by hjsg** [huiyan-fe/react-bmap#70]
首先引入图片
`import eleboxImg from '@src/assets/online-elebox.png'`
设置Marker的icon
`icon={eleboxImg}`
**然后没有效果**

**Comment by Junior2Ran** [comment]
`icon`属性不支持**图片路径**，只支持内置属性名和`BMap.Icon`类。
如果要使用自定义图片icon有两个方法：
1. 自定义一个`BMap.Icon`对象，然后传给`<Marker>`的`icon`属性
2.使用自定义覆盖物`<Marker>Your Icon Div</Marker>`
