### ISSUE TITLE
飞线图问题： 当两点的lng一正一负时，连不上飞线

### ISSUE THREAD

**Issue by duanshanshan7** [huiyan-fe/react-bmap#75]
![image](https://user-images.githubusercontent.com/24423903/68762557-61bb3d80-0651-11ea-93d1-bd9f74394fbb.png)

**Comment by Junior2Ran** [comment]
图中有什么问题吗？marker和4我看线是连上的
一正一负的时候，试试负数+180能否解决

**Comment by duanshanshan7** [comment]
就是  比如说英国跟法国的lon一个是正一个是负的时候，英法之间的连线就不会出来，加180不行，点跑了，请问这个改怎么解决呢？谢谢
![image](https://user-images.githubusercontent.com/24423903/68928677-a667e580-07c5-11ea-967f-b68cd19c764c.png)
![image](https://user-images.githubusercontent.com/24423903/68928784-e29b4600-07c5-11ea-9150-77dcd7d61892.png)

**Comment by Junior2Ran** [comment]
这个可能是mapv在计算负坐标生成曲线时造成的问题，可以用直线吗？

**Comment by duanshanshan7** [comment]
之前这个问题（一正一负时，连不上飞线）已经解决了，现在有个新的问题，地图上面overlay多了之后，清楚overlay没有进行垃圾回收，如此操作多次之后页面会发生崩溃（手机页面居多）出现白屏的情况，请问这个能做一些优化吗？谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"后悔编程哥"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月25日(星期一) 中午1:29
收件人:&nbsp;"huiyan-fe/react-bmap"<react-bmap@noreply.github.com&gt;;
抄送:&nbsp;"姗姗"<787938906@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [huiyan-fe/react-bmap] 飞线图问题： 当两点的lng一正一负时，连不上飞线 (#75)




这个可能是mapv在计算负坐标生成曲线时造成的问题，可以用直线吗？

**Comment by Junior2Ran** [comment]
用了多少个layer？能复用的layer尽量通过修改data或者options来达成预期效果

**Comment by xwg2015** [comment]
@Junior2Ran 
大佬 组件销毁的时候也用了layer.destroy() 感觉并没有作用 能不能帮看下

**Comment by duanshanshan7** [comment]
因为需要页面和tab切换，切换次数多的时候就会崩溃，&nbsp;组件销毁的时候也用了layer.destroy() 感觉并没有作用， 能不能帮看下，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"后悔编程哥"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月16日(星期一) 上午10:31
收件人:&nbsp;"huiyan-fe/react-bmap"<react-bmap@noreply.github.com&gt;;
抄送:&nbsp;"姗姗"<787938906@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [huiyan-fe/react-bmap] 飞线图问题： 当两点的lng一正一负时，连不上飞线 (#75)




用了多少个layer？能复用的layer尽量通过修改data或者options来达成预期效果

**Comment by Junior2Ran** [comment]
@xwg2015 @duanshanshan7 
layer.destroy的bug是依赖mapv中的bug导致，现已在`mapv@2.0.42`版本修复。
react-bmap也更新了mapv依赖版本，发布了`react-bmap@1.0.108`，升级到最新版本即可。
