### ISSUE TITLE
不支持服务端渲染

### ISSUE THREAD

**Issue by PerryHuan9** [huiyan-fe/react-bmap#79]
在结合next使用时：
   在自定义的_document.tsx中引入
`<script
            type="text/javascript"
            src="http://api.map.baidu.com/api?v=3.0&ak=ESajoXZDL7BHBV40luHIxBCK64o1Ptgm"
          />
`
结果还是报  BMap is not defined

**Comment by sunui** [comment]
浏览器报的还是服务端报的

**Comment by PerryHuan9** [comment]
之前是浏览器端报的，后来突然就可以了
