### ISSUE TITLE
CustomOverlay Markers does not support Events / BMap.Marker is not added if there is a CustomOverlay

### ISSUE THREAD

**Issue by williamli** [huiyan-fe/react-bmap#8]
If Marker contains children, BMap.Marker is not created and`bindEvent` is not called.

https://github.com/huiyan-fe/react-bmap/blob/1d4a00565b98da9378e0c54e6a6281313061fca2/src/components/marker.js#L163-L173

**Comment by hinikai** [comment]
Thank you for your feedback. The problem has been solved in version 1.0.39 at npm. you can update it and see this example to use.

> 
    <Marker position={{lng: 109.430831, lat: 38.211366}} offset={new BMap.Size(-75, -60)}>
        <div onClick={function(){alert(1)}} style={{width: '150px', height: '40px', lineHeight: '40px', background: 'red', textAlign: 'center'}}>自定义覆盖物</div>
    </Marker>

**Comment by williamli** [comment]
works fine.
