### ISSUE TITLE
驾车路线的起终点的提示框问题

### ISSUE THREAD

**Issue by carryonZhang** [huiyan-fe/react-bmap#9]
你好！我想问一下
<img width="408" alt="2017-08-31 6 04 21" src="https://user-images.githubusercontent.com/20091023/29918142-ea43f67e-8e76-11e7-971e-e79f8c0bf10d.png">
这个起点的弹窗我想改成InfoWindow那样的形式，可不可以？

**Comment by Junior2Ran** [comment]
暂未提供该API
question out of date, closed.
