### ISSUE TITLE
ts项目里报错。。。。。

### ISSUE THREAD

**Issue by xu-Aurora** [huiyan-fe/react-bmap#93]
有@types/react-bmap这个包吗？
在ts项目中报错叫我执行npm install @types/react-bmap操作，执行这个操作结果报错，这怎么搞？

**Comment by iamppz** [comment]
``` typescript
// @ts-ignore
import { Map, NavigationControl } from "react-bmap";
```

**Comment by jaywcjlove** [comment]
@xu-Aurora https://github.com/uiwjs/react-baidu-map 支持 TypeScript

**Comment by Junior2Ran** [comment]
没有@types/react-bmap，该组件库不支持ts，建议使用`@ts-ignore`忽略报错
或者使用最新的依赖GL版JSAPI开发的[react-bmapgl](https://github.com/huiyan-fe/react-bmapgl)组件库，支持ts

**Comment by jaywcjlove** [comment]
@Junior2Ra @types/react-bmap 已经集成到 https://github.com/uiwjs/react-baidu-map 中了。
